// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wireinject

import (
	"github.com/devanadindraa/Evermos-Backend/database"
	"github.com/devanadindraa/Evermos-Backend/domains/category"
	"github.com/devanadindraa/Evermos-Backend/domains/provcity"
	"github.com/devanadindraa/Evermos-Backend/domains/shop"
	"github.com/devanadindraa/Evermos-Backend/domains/user"
	"github.com/devanadindraa/Evermos-Backend/middlewares"
	"github.com/devanadindraa/Evermos-Backend/routes"
	"github.com/devanadindraa/Evermos-Backend/utils/config"
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
)

import (
	_ "github.com/google/subcommands"
)

// Injectors from wire.go:

func initializeDependency(config2 *config.Config) (*routes.Dependency, error) {
	db, err := database.NewDB(config2)
	if err != nil {
		return nil, err
	}
	service := user.NewService(config2, db)
	middlewaresMiddlewares := middlewares.NewMiddlewares(config2, service)
	validate := NewValidator()
	handler := user.NewHandler(service, validate)
	provcityProvcity := provcity.NewEmsiaClient(config2)
	provcityHandler := provcity.NewProvcityHandler(provcityProvcity)
	categoryService := category.NewService(config2, db)
	categoryHandler := category.NewHandler(categoryService, validate)
	shopService := shop.NewService(config2, db)
	shopHandler := shop.NewHandler(shopService, validate)
	dependency := routes.NewDependency(config2, middlewaresMiddlewares, db, handler, provcityHandler, categoryHandler, shopHandler)
	return dependency, nil
}

// wire.go:

var userSet = wire.NewSet(user.NewService, user.NewHandler)

var provcitySet = wire.NewSet(provcity.NewEmsiaClient, provcity.NewProvcityHandler)

var categorySet = wire.NewSet(category.NewService, category.NewHandler)

var shopSet = wire.NewSet(shop.NewService, shop.NewHandler)

func NewValidator() *validator.Validate {
	return validator.New()
}
